export const FETCH_DOCTORS_REQUEST = 'FETCH_DOCTORS_REQUEST';
export const FETCH_DOCTORS_SUCCESS = 'FETCH_DOCTORS_SUCCESS';
export const FETCH_DOCTORS_FAILURE = 'FETCH_DOCTORS_FAILURE';

export const FETCH_DOCTOR_BY_ID = 'FETCH_DOCTOR_BY_ID';
export const ADD_DOCTOR = 'ADD_DOCTOR';
export const EDIT_DOCTOR = 'EDIT_DOCTOR';
export const DELETE_DOCTOR = 'DELETE_DOCTOR';
